---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-7.0
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[starter::default]
    attributes:

  - name: geoserver
    run_list:
      - recipe[geoserver::default]
    attributes:

  - name: bryankaraffa.com
    run_list:
      - recipe[bryankaraffacom::default]
    excludes:
       - ubuntu-12.04
    attributes:
